{% set name = "pip-system-certs" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pip_system_certs-{{ version }}.tar.gz
  sha256: db8e6a31388d9795ec9139957df1a89fa5274fb66164456fd091a5d3e94c350c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - git-versioner
  run:
    - python >={{ python_min }}
    - wrapt >=1.10.4

about:
  home: https://gitlab.com/alelec/pip-system-certs
  summary: Live patches pip and requests to use system certs by default
  description: |
    pip-system-certs patches pip and requests at runtime to use certificates
    from the default system store (rather than the bundled certs ca).

    This will allow pip to verify tls/ssl connections to servers whose cert is
    trusted by your system install.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://gitlab.com/alelec/pip-system-certs

extra:
  recipe-maintainers:
    - adament
